### ISSUE TITLE
Pre-official characters alphabet notation?

### ISSUE THREAD

**Issue by xtetsuji** [htk291/p5-Acme-PriPara#1]
![refer](http://event.goodsmile.info/wp-content/uploads/2014/12/pri_clear-file.jpg)

But I think this information is not certain.

1. "Reona" is not canonical. "Leona" is canonical. "Reona" notation may be Japanese roma-ji notation.
2. Most /sofi/ pronunciation spellling is "Sophie".

**Comment by htk291** [comment]
fixed in commit 1e6e00a9458c312be11ed73781b7567f734c6e18
thanks for your notification.
