### ISSUE TITLE
Add character-says

### ISSUE THREAD

**Issue by Kiryuanzu** [htk291/p5-Acme-PriPara#8]
I want to add characters say.

`is $mirei->say,           'ぷり';`
`is $sophy->say,            'ぷしゅ〜';`
`is $sion->say,            'イゴッ!';`
`is $dorothy->say,         'テンションマーックス!';`
`is $reona->say,           'リラックス〜。';`

Now, The dialogue of characters other than lala is not yet in it.

I create Pull request.
If you are fine it , please check the request.

**Comment by AnaTofuZ** [comment]
@Kiryuanzu ++ 👍 👍 👍 

![COqmN-8VAAAHn98](https://user-images.githubusercontent.com/13062611/64522441-f0030280-d334-11e9-9af3-4d6866ec364f.jpg)
